ALTER TABLE camps ADD COLUMN IF NOT EXISTS camp_dates text;
ALTER TABLE camps ADD COLUMN IF NOT EXISTS itinerary text;
ALTER TABLE camps ALTER COLUMN start_date DROP NOT NULL;
ALTER TABLE camps ALTER COLUMN end_date DROP NOT NULL;
